### ISSUE TITLE
small rational number whose denominator exceeds bounds breaks sim on iPad 2

### ISSUE THREAD

**Issue by ghost** [phetsims/equality-explorer#134] opened 2018-07-03 18:56 UTC
<b>Test Device</b>

Tycho

<b>Operating System</b>

iOS 9.3.5

<b>Browser</b>

Safari 9.0 Mobile

<b>Problem Description</b>

For phetsims/QA/issues/131.

@andrealin found an interesting bug... 

In the Operations screen, making a rational number (_p/q_, where _p_ and _q_ are integers) whose denominator, _q_, is greater than 1 billion (10^9), breaks the sim. (See the video.)

This phenomenon does not occur for a rational number (_p/q_, where _p_ and _q_ are integers) whose numerator, _p_, exceeds 1 billion (10^9). In this case, the usual warning message is given.

<b>Steps to Reproduce</b>

1. Operations screen.
2. Add 1.
3. Divide by 10.
4. Repeat step 3 until denominator is 10^9.
5. Divide by 10 one more time; the sim should break.

<b>Visuals</b>

https://drive.google.com/open?id=1qvaDP_sOvLenqusaOmLRCdvop6jpNmup

<details>
<summary><b>Console Messages</b></summary>

Console for [all_phet.html](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.125/phet/equality-explorer_all_phet.html):

```
[Log] Go + 1 (equality-explorer_all_phet.html, line 1183)
[Log] Go ÷ 10 (equality-explorer_all_phet.html, line 1183, x10)
[Log] maxInteger exceeded (equality-explorer_all_phet.html, line 1183)
```

Console for [all_phet_debug.html](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.125/phet/equality-explorer_all_phet.html):

```
[Log] Go + 1 (equality-explorer_all_phet_debug.html, line 29573)
[Log] Go ÷ 10 (equality-explorer_all_phet_debug.html, line 29573, x10)
[Log] Assertion failed: numerator must be an integer: NaN (equality-explorer_all_phet_debug.html, line 28463)
[Error] Error: Assertion failed: numerator must be an integer: NaN
	(anonymous function) (equality-explorer_all_phet_debug.html:28464)
	numerator (equality-explorer_all_phet_debug.html:35563)
	setToSum (equality-explorer_all_phet_debug.html:35718)
	subtract (equality-explorer_all_phet_debug.html:35758)
	minus (equality-explorer_all_phet_debug.html:35769)
	(anonymous function) (equality-explorer_all_phet_debug.html:115321)
	listener (equality-explorer_all_phet_debug.html:84676)
	emit2 (equality-explorer_all_phet_debug.html:39184)
	_notifyListeners (equality-explorer_all_phet_debug.html:39697)
	_setAndNotifyListeners (equality-explorer_all_phet_debug.html:39684)
	set (equality-explorer_all_phet_debug.html:39631)
	listener (equality-explorer_all_phet_debug.html:84676)
	emit2 (equality-explorer_all_phet_debug.html:39184)
	_notifyListeners (equality-explorer_all_phet_debug.html:39697)
	_setAndNotifyListeners (equality-explorer_all_phet_debug.html:39684)
	set (equality-explorer_all_phet_debug.html:39631)
	value (equality-explorer_all_phet_debug.html:39726)
	updateWeightOnPlateProperty (equality-explorer_all_phet_debug.html:87182)
	(anonymous function)
	(anonymous function) (equality-explorer_all_phet_debug.html:86788)
	emit2 (equality-explorer_all_phet_debug.html:39184)
	_notifyListeners (equality-explorer_all_phet_debug.html:39697)
	_setAndNotifyListeners (equality-explorer_all_phet_debug.html:39684)
	set (equality-explorer_all_phet_debug.html:39631)
	listener (equality-explorer_all_phet_debug.html:84676)
	emit2 (equality-explorer_all_phet_debug.html:39184)
	_notifyListeners (equality-explorer_all_phet_debug.html:39697)
	_setAndNotifyListeners (equality-explorer_all_phet_debug.html:39684)
	set (equality-explorer_all_phet_debug.html:39631)
	set (equality-explorer_all_phet_debug.html:71285)
	push (equality-explorer_all_phet_debug.html:86473)
	putTermOnPlate (equality-explorer_all_phet_debug.html:87023)
	applyOperation (equality-explorer_all_phet_debug.html:87278)
	(anonymous function) (equality-explorer_all_phet_debug.html:125465)
	forEach
	applyOperation (equality-explorer_all_phet_debug.html:125464)
	(anonymous function) (equality-explorer_all_phet_debug.html:126621)
	emit2 (equality-explorer_all_phet_debug.html:39184)
	_notifyListeners (equality-explorer_all_phet_debug.html:39697)
	_setAndNotifyListeners (equality-explorer_all_phet_debug.html:39684)
	set (equality-explorer_all_phet_debug.html:39631)
	set (equality-explorer_all_phet_debug.html:71285)
	value (equality-explorer_all_phet_debug.html:39726)
	onComplete (equality-explorer_all_phet_debug.html:126642)
	(anonymous function) (equality-explorer_all_phet_debug.html:126160)
	emit (equality-explorer_all_phet_debug.html:39138)
	step (equality-explorer_all_phet_debug.html:83238)
	step (equality-explorer_all_phet_debug.html:126174)
	(anonymous function) (equality-explorer_all_phet_debug.html:126729)
	forEach
	step (equality-explorer_all_phet_debug.html:126728)
	step (equality-explorer_all_phet_debug.html:127796)
	step (equality-explorer_all_phet_debug.html:124000)
	stepSimulation (equality-explorer_all_phet_debug.html:134124)
	stepOneFrame (equality-explorer_all_phet_debug.html:134043)
	runAnimationLoop (equality-explorer_all_phet_debug.html:134026)
	(anonymous function)
```

</details>

**Comment by megan-phet** [comment] 2018-07-03 22:33
It is posible to do this in the "Solve It!" screen as well, on the same device.

**Comment by pixelzoom** [comment] 2018-07-05 19:00
I confirmed that this does not happen on desktop (e.g. macOS + Chrome).  Very odd.

**Comment by ghost** [comment] 2018-07-05 19:02
@pixelzoom, also does not occur on latest iOS. [CM edit: latest = 11]

**Comment by pixelzoom** [comment] 2018-07-05 19:05
@lmulhall-phet Is it a problem on iOS 10, or specific to iOS 9?

**Comment by pixelzoom** [comment] 2018-07-05 19:12
"Assertion failed: numerator must be an integer: NaN" occurs in PHETCOMMON/Fraction.

**Comment by ghost** [comment] 2018-07-05 19:19
@pixelzoom, my iOS 10 device was accidentally updated to iOS 11 a few ~~weeks~~ (EDIT: months, maybe?) ago, and Apple stopped signing iOS 10.3.3 in 2017, I think. I'll check on iOS 12, as it's the only other iOS I can test on atm. I can look into other ways to downgrade to iOS 10, but it won't be through iTunes.

**Comment by ghost** [comment] 2018-07-05 19:51
Confirmed does not occur on iOS 12.

According to @phet-steele:
- Our iOS 10 device was accidentally updated to iOS 11 after Apple stopped signing iOS 10.3.3.
- "iOS 10 has NEVER been uniquely problematic."

**Comment by pixelzoom** [comment] 2018-07-06 18:13
> "iOS 10 has NEVER been uniquely problematic."

Just because a problem has not previously occurred, that is not justification for not testing on a supported platform.  And it could also provide important information on whether an issue (like this one) is definitively specific to one OS/browser version.   So I highly recommend that PhET figure out how to get an iOS 10 test device into service.

**Comment by ghost** [comment] 2018-07-06 19:05
> Just because a problem has not previously occurred, that is not justification for not testing on a supported platform.

I agree, @pixelzoom.

> I highly recommend that PhET figure out how to get an iOS 10 test device into service.

It would be nice to get some input from @ariel-phet and @phet-steele.

**Comment by phet-steele** [comment] 2018-07-06 19:45
> Just because a problem has not previously occurred, that is not justification for not testing on a supported platform.

Sure, but it's also not justification that we MUST test on that platform.

> So I highly recommend that PhET figure out how to get an iOS 10 test device into service.

Short of buying a brand new/used iPad that miraculously has the iOS we want and not the latest iOS instead, I don't see an easy way to get an iOS 10 device. Apple makes it impossible to downgrade once they stop signing OSes. I'd recommend looking at usage statistics for this iOS, because if it's low enough then it wouldn't matter if the problem occurs on iOS 10 or not. Furthermore, iOS 10 is probably becoming obsolete with the imminent release of iOS 12, and it really isn't worth it for PhET to continue to spend time testing old iOSes anyway. We don't want a situation where PhET is testing iOS 9, 10, 11, & 12.

My final two cents: whether or not this issue occurs on iOS 10 is probably not worthwhile to find out. I'm not a developer, but honestly how much good could it do? It might do some good, but I don't think it will lead to some anagnorisis. The time-cost to get a hold of iOS 10 is probably not worth it anymore. We already know that this issue does not occur on iOS 11, and if history is anything meaningful, iOS 10 has not been problematic if iOS 11 passes.

**Comment by pixelzoom** [comment] 2018-07-06 19:53
@phet-steele said:
> Sure, but it's also not justification that we MUST test on that platform.

I don't follow your logic.  In general, if PhET is advertising that a platform is "supported", then that seems like "justification" (or perhaps even a requirement) to test on that platform.  And iOS 10 is a supported platform.  From the System Requirements FAQ:

> iPad: iOS 9+ Safari. The HTML5 PhET sims are supported on iPad2 or later.

**Comment by amanda-phet** [comment] 2018-07-06 20:10
If we are still supporting iOS9 then we should still fix this bug. 

If we decide to stop supporting iOS9, then we will need to figure out if we are supporting iOS10+ or iOS11+. 

@ariel-phet might need to weigh in on this.

**Comment by ghost** [comment] 2018-07-06 20:25
@phet-steele is right, getting an iOS 10 device would be difficult.

@amanda-phet also makes a good point. At some point, we'll drop support for iOS 9, and then we would be forced to drop support for iOS 10 if we don't have an iOS 10 device.

Perhaps the solution should be supporting the two latest iOS versions. When iOS 12 is released, we drop support for iOS 9 and iOS 10. (Obviously, we can only do this if iOS 9 and iOS 10 usage is low.)

**Comment by pixelzoom** [comment] 2018-07-06 21:15
Moving the discussion about which iOS versions should be supported and tested to https://github.com/phetsims/tasks/issues/943, assigned to @ariel-phet.  Until I hear otherwise, I am expecting Equality Explorer RC1 to be tested on iOS 9, 10 and 11.

**Comment by pixelzoom** [comment] 2018-07-09 15:03
I verified that this is a problem only for the denominator.   

I also noticed that if the max is reduced to `?maxInteger=100000000` (1E^8), this is not a problem.

**Comment by pixelzoom** [comment] 2018-07-09 15:39
Hmmm.... Looking at the console output, the error message is:

`Assertion failed: numerator must be an integer: NaN (equality-explorer_all_phet_debug.html, line 28463)
[Error] Error: Assertion failed: numerator must be an integer: NaN`

I would have expected the problem to be with the _denominator_, but something's going wrong with the numerator.  And the problem looks to be in Fraction `setSumTo`.

**Comment by pixelzoom** [comment] 2018-07-09 17:17
I added the follow to PHETCOMMON/Fraction.setSumTo:

```js
      if ( lcm === Infinity ) {
        alert( 'setSumTo: lcm=' + lcm +
               ', numerator1=' + numerator1 +
               ', denominator1=' + denominator1 +
               ', numerator2=' + numerator2 +
               ', denominator2=' + denominator2  );
      }
```

When the error occurs on iPad2, the alert shows:

> setSumTo: lcm=Infinity, numerator1=1, denominator1=10000000000, numerator2=1, denominator2=10000000000

Note that the denominators are 1E10.

Confirming in the Web Inspector console:

```
> phet.dot.Util.lcm( 10000000000, 10000000000 )
Infinity
```
 
On Chrome desktop:

```
> phet.dot.Util.lcm( 10000000000, 10000000000 )
10000000000
```

So it appears that we have a problem with `Util.lcm` on iPad2.

**Comment by pixelzoom** [comment] 2018-07-09 17:26
`Util.lcm` uses `Util.gcd`.

Chrome desktop:

```
> phet.dot.Util.gcd( 1e10, 1e10 )
> 10000000000
```

Safari + iOS9:

```
> phet.dot.Util.gcd( 1e10, 1e10 )
> 2.65249474e-315
```

And Util.gcd uses `%`, and on Safari iOS9:

```
> 1e10 % 1e10
2.65249474e-315
> 1e9 % 1e9
0
```

So there appears to be a problem with `%` on Safari + iOS9.

**Comment by pixelzoom** [comment] 2018-07-09 18:16
This was fixed in https://github.com/phetsims/dot/issues/75 by creating `Util.mod` as a replacement for `%`, then using `Util.mod` in `Util.gcd`.   

@lmulhall-phet please verify in master.

**Comment by ghost** [comment] 2018-07-11 23:04
Fixed in master!

**Closed as completed** 2018-07-11 23:09 UTC
Labels: type:bug, priority:2-high
