### ISSUE TITLE
Beating Level 5 leads to sim freezing on victory screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#170] opened 2021-11-05 19:30 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/732. `?showAnswers` was used to move through the level quickly. This happens when all game levels are available and with `?gameLevels=5`
When the 10th question of level 5 is beaten, the win sound and dialog appear, but no confetti does and the sim completely freezes. The console error is bellow.

**Visuals**
<img width="960" alt="beatlevel5" src="https://user-images.githubusercontent.com/41024075/140567931-0d7ea9a7-c31f-4cde-af88-1b8eef071b89.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Equality Explorer‬
URL: https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.4/phet/equality-explorer_all_phet.html?showAnswers&gameLevels=5
Version: 1.1.0-dev.4 2021-11-03 18:34:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2021-11-05 20:26
Duplicate of https://github.com/phetsims/equality-explorer/issues/169.  Closing.

**Closed as completed by pixelzoom** 2021-11-05 20:26 UTC
Labels: type:bug
