### ISSUE TITLE
Min/Max sound missing for multiplication/division object pickers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#223] opened 2024-11-22 15:46 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1175, in the Operations and Solve It! Screens, because the multiplication/division number pickers don't have the terms 10x and -10x, they are missing the min/max sounds that are heard with all the other number pickers in the sim. 

**Steps to reproduce**
1. Go to the Operations screen, press and hold the up arrow until the max value, 10x, is reached
2. Press Reset All
3. Select Multiplication Symbol
4. Press and hold the up arrow until the max value, 10, is reached
5. Repeat with minimum values

**Visuals**

https://github.com/user-attachments/assets/dde19d6c-f5cc-4399-92ac-ab0e5015b13e

**Comment by pixelzoom** [comment] 2024-11-22 15:57
Good find. Reproduced in main.

FYI, this is not actually a NumberPicker.  It's a UI component called ObjectPicker, created specifically for Equality Explorer.  I recently added sounds to it, using the same defaults as NumberPicker. What I didn't account for is that the "items" in the picker vary depending on the selected operation.

It was necessary to create ObjectPicker because choices like "10x" are not numbers.  If another sim needs something like this, ObjectPicker may someday be migrated to common code.

**Comment by pixelzoom** [comment] 2024-11-22 16:08
Note to self: ObjectPicker is only used in the _Operations_ and _Solve It!_ screens of the Equality Explorer sim, so the other 2 sims in the suite will not need to be patched.

**Comment by pixelzoom** [comment] 2024-11-22 17:05
Fixed in main and 1.2 branches for equality-explorer.  Irrelevant for equality-explorer-basics and equality-explorer-two-variables, see https://github.com/phetsims/equality-explorer/issues/223#issuecomment-2494115211.

@Nancy-Salpepi please test in main. If it looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment] 2024-11-22 17:25
Sounds good in main.

**Comment by pixelzoom** [comment] 2024-11-26 20:01
Ready for spot-check in https://github.com/phetsims/qa/issues/1180, where it's relevant in the _Operations_ and _Solve It!_ screens.  This issue is not relevant for equality-explorer-basics and equality-explorer-two-variables.

Please close if it looks OK.

**Comment by KatieWoe** [comment] 2024-11-26 21:20
Looks good in rc.2

**Closed as completed by KatieWoe** 2024-11-26 21:20 UTC
Labels: type:bug, status:ready-for-review, dev:sound
