### ISSUE TITLE
items for "Basics" screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#6] opened 2017-09-01 21:45 UTC
The "Basics" screen is cruising towards feature completeness, and I'm starting to tweak layouts, etc.  So we need to make a decision about the item icons.  

From 6/8/2017 meeting notes in the [design doc](https://docs.google.com/document/d/1xu9nawWcndFqgg5zyCGm25h-OFUsuFYnXF3QHW42spQ/edit#heading=h.o05zor9rg52o):

>**Issue**: Items in carousel on first screen
>
> **Discussion**: 
> 
> Thoughts? 
> 
> AM: I think it would be fun to include objects from other sims, but I’m mostly familiar with the recent math sims. Other ideas? Fruit is very approachable. Polygons can look mysterious. Balloons look funny to me in this context. 
> 
> ![screenshot_375](https://user-images.githubusercontent.com/3046552/29988750-16ddfb0c-8f2c-11e7-942a-c0b6811a30fa.png)
> 
> Animals? Bunnies… 
Stick figures
Shapes 
CCK grab bag items
Coins from ExEx
FB shapes? 
Cars from unit rates
Balancing act: presents, tv, puppies, rocks
> 
> **Decision**:

**Comment by pixelzoom** [comment] 2017-09-01 21:53
Important considerations:

• Icons are arranged in a 2D grid on the scale. All cells in the grid have the same dimensions.  The cell dimensions are determined by determining the maximum width and maximum height of all icons. Icons are positioned on the bottom center of each cell. (Run with `?showGrid` to see the grid.)

• Icons should have similar heights so that they stack nicely on the scale.  If you want no vertical space between stacked items, then icons should have identical heights.  If heights are not the same, then some icons will look like they are floating when stacked.

• Similarly for width, if you want to minimize horizontal space between stacks of icons, then icons should have similar or identical widths. (This is probably less of a concern than icon height.)

• When considering the shapes of icons, think about how they will stack.  For example, stacking a hexagon on top of a triangle looks a little odd (but may be OK, that's up to you.)

**Comment by pixelzoom** [comment] 2017-09-08 22:09
I'll also need to know the "weight" for each Item.  For example, items in the "fruit" scene are currently using the following weights: apple=3, orange=2, one=1.

**Comment by pixelzoom** [comment] 2017-09-22 19:51
Also keep in mind that the item with the most weight determines how much (or how little) the scale will move per unit weight.   For example, with apple=3, orange=2, one=1, you can clearly see the "ones" move.  If you decide on apple=6, orange=3, one=1, then the "ones" will move half as much as they do now.

**Comment by pixelzoom** [comment] 2017-09-27 20:55
In 9/27/17 design meeting, we decided to add a 4th scene to Basics.

Raising priority of this issue to "top".  There are so many layout and behavior issues related to the items that we need these asap.

**Comment by pixelzoom** [comment] 2017-09-28 17:40
To summarize what I need...

For each scene:
• the items
• the order of the items in the panel
• which item to use on the radio button to select the scene
• the max weight for the scale (if different than 30)

For each item:
• icon
• drop shadow
• weight

**Comment by amanda-phet** [comment] 2017-09-28 20:15
update: since we decided to add a fourth scene, I won't have artwork for that scene for at least a few days (I am working with Cheryl and she is going to draw some animals). 

Would it be useful for you to have all of the above info for the first three scenes, which I know for sure? Or just wait until you have all of it at once?

**Comment by pixelzoom** [comment] 2017-09-28 20:20
I'll take the first 3 screens whenever they're ready.

**Comment by amanda-phet** [comment] 2017-09-28 20:32
![screen shot 2017-09-28 at 2 31 04 pm](https://user-images.githubusercontent.com/7852916/30989086-b0bf89c4-a459-11e7-98e8-b1bfc36fded9.png)

Emailing you the .ai file now. I have one file for objects without shadows and another for objects with shadows. If you prefer to have separate .ai files for every object let me know, they can be organized that way instead. (so, apple without and apple with shadow would be in one file).

**Comment by pixelzoom** [comment] 2017-09-28 20:44
When doing the icons for 4th scene (animals), reminder that they will be scaled _way_ down in the Snapshots accordion box.  So recommended to avoid unnecessary detail, and make them different enough that it’s easy to tell them apart when they’re very tiny.

**Comment by pixelzoom** [comment] 2017-09-29 03:21
@amanda-phet I've integrated the images for the first 3 scenes into [1.0.0-dev.25](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.25/equality-explorer_en.html), no drop shadows yet.  

Thoughts on the icons:

• Two of the coins have a lot of light gray in them, which doesn't work too well on the light yellow screen background and gray scale plates. The coin with the triangle on it feels especially blah.

• Having a lot of yellow items (lemons, coins) feels like it deemphasizes the yellow buttons. Should we avoid yellow items, so that the buttons remain prominent?

**Comment by pixelzoom** [comment] 2017-09-29 03:30
In the code, I'm referring to scenes 1-4 as the "shapes", "fruits", "coins" and "animals" scenes respectively.  Let me know if you'd like to use different names.

**Comment by amanda-phet** [comment] 2017-09-29 15:47
The coins look a little blah, I agree... Maybe I'll swap out the gray one with a different one. The problem is all of the coins have those colors in them, to look slightly metallic, so I may need to go back to the drawing board for that one. I wish I could use those cute veggies but I'm concerned about how they might stack. 

I think the lemons look nice and in general I like the fruits, so I'd rather just change the color of the organize button. I have a design for that button that I still need to give you, so let's just change the color of that button (thinking light blue, like the play button color). I'll respond directly to that issue. 

Those scene names sound great to me.

**Comment by amanda-phet** [comment] 2017-09-29 17:40
This is what the veggies could look like if stacked in the grid. There is obviously a lot of space between the objects.. is it too strange? @ariel-phet @kathy-phet thoughts?

<img width="503" alt="screen shot 2017-09-29 at 11 41 50 am" src="https://user-images.githubusercontent.com/7852916/31028444-3d2dd7ba-a50b-11e7-9eff-d2378c01f938.png">

**Comment by pixelzoom** [comment] 2017-09-29 19:49
Veggies stacks look very strange to me.  Also possibly more difficult to count.

**Comment by ariel-phet** [comment] 2017-09-29 21:23
@amanda-phet not a fan of the veggies (except for sending a healthful message!)

It seems reasonable "square" aspect ration items are best

**Comment by kathy-phet** [comment] 2017-09-29 21:27
Agreed. Veggies look odd.

**Comment by pixelzoom** [comment] 2017-09-29 21:52
How about beer cans :)

**Comment by amanda-phet** [comment] 2017-09-29 22:27
Those would stack nicely!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pixelzoom** [comment] 2017-09-29 22:37
Updated coin icons appear in http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.26/equality-explorer_en.html.

**Comment by pixelzoom** [comment] 2017-10-03 16:14
In phetsims/tasks#894:
> @clmccutchan is creating a tiny dog, cat, and turtle for the fourth scene.

**Comment by pixelzoom** [comment] 2017-10-03 16:18
@amanda-phet @clmccutchan Please add the artwork for the "Animals" scene to the existing .ai files, not in a new .ai file.  The existing .ai files should be obtained from GitHub, so that you have the latest versions (with the hex coin rotated).  Those files are:

https://github.com/phetsims/equality-explorer/blob/master/assets/basics-artwork-shadows.ai
https://github.com/phetsims/equality-explorer/blob/master/assets/basics-artwork-without-shadow.ai

**Comment by clmccutchan** [comment] 2017-10-03 16:37
@pixelzoom Will do! @amanda-phet will know which scene this are for far better than I.

**Comment by amanda-phet** [comment] 2017-10-03 16:39
I'll take care of anything to do with the assets once we have the final artwork from @clmccutchan .

**Comment by amanda-phet** [comment] 2017-10-17 20:36
updated .ai files have been committed. @pixelzoom let me know if you'd like me to export the images as well.

**Comment by pixelzoom** [comment] 2017-10-18 14:54
I'll handle creation of PNG files.

**Comment by pixelzoom** [comment] 2017-10-18 16:49
Here's a dev version with the animal icons integrated, and "worst case" scenario shown in the Snapshots accordion box:
https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.32/equality-explorer_en.html

Questions:

• Shadows don't look great.  Can we live with this? Our shadow offset (4,4) doesn't really work for these icons because they are unlike the icons in the other scenes. They are more complicated shapes, with more detail.  We could use a different (smaller) shadow offset, but the offset would be so small that the shadow wouldn't be effective.

• Detail is lost in Snapshot equations.  Is this a problem? What about mobile devices?

• Is black a good choice for the cat? In other scenes, we've used colorful icons, and black has been reserved for numbers and math symbols.

**Comment by amanda-phet** [comment] 2017-10-18 16:58
The dog looks like it has the shadow of a cat, so fixing that might help improve the shadow issue. 

I think the shadows are fine, personally. It could the the fact that the shadow is visible under the small tail, so we could try reflecting the cat and dog. 
<img width="248" alt="screen shot 2017-10-18 at 10 54 35 am" src="https://user-images.githubusercontent.com/7852916/31731590-c4bcb7dc-b3f2-11e7-9442-98d86b4ff6a8.png">

I'm not concerned about detail in the snapshots, only that they can be interpreted correctly. 

You're right about the black cat.. once I saw it in the equation I realized it blends in a little bit with the numbers. Maybe gray would be better?
<img width="373" alt="screen shot 2017-10-18 at 10 57 49 am" src="https://user-images.githubusercontent.com/7852916/31731742-35e0fa0e-b3f3-11e7-8e83-a881ed565e61.png">

**Comment by pixelzoom** [comment] 2017-10-18 17:04
The dog shadow is indeed incorrect.  I had fixed it, but forgot to rebuild the dev version before publishing.

Reflecting the dog and cat will indeed reduce the shadow problem.

Gray cat will have the same problem as gray coins - it will disappear on the plates.

Let me know how you want to proceed.

**Comment by kathy-phet** [comment] 2017-10-18 17:04
Maybe with a black stroke around that cat features, like the dog has? 

@amanda-phet - I also noticed that the 2nd and 3rd coins look pretty similar in the equation - since they have the same base color. Can the third one be all silver, or somehow a bit more distinctive from the 2nd at that small scale 

And perhaps at the small scale, a one pixel stroke around the outside of the image could help make it more defined in the equations.

**Comment by pixelzoom** [comment] 2017-10-18 17:05
@kathy-phet asked:
>  I also noticed that the 2nd and 3rd coins look pretty similar in the equation - since they have the same base color. Can the third one be all silver, or somehow a bit more distinctive from the 2nd at that small scale

We tried silver coins. They disappear on the gray plate.

**Comment by pixelzoom** [comment] 2017-10-18 17:07
@kathy-phet said:
> And perhaps at the small scale, a one pixel stroke around the outside of the image could help make it more defined in the equations.

We do not have separate icons for "the small scale".   Because the scale varies dynamically for equations (based on how much space is available) we need to use the same icons everywhere.

**Comment by amanda-phet** [comment] 2017-10-18 17:09
@kathy-phet we could try this two-toned coin instead, if you think it would provide more contrast than the current one. I suspect it will.
<img width="64" alt="screen shot 2017-10-18 at 11 07 46 am" src="https://user-images.githubusercontent.com/7852916/31732147-ac0f0d00-b3f4-11e7-8088-6043dc9d22ea.png">

The gray cat would need a black stroke similar to the dog, I just didn't get a chance to work that in to the quick mockup.

**Comment by pixelzoom** [comment] 2017-10-18 17:15
Here's a dev version with the dog and cat reflected about the y axis:
https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.33/equality-explorer_en.html

If we like the reflected dog and cat, we need to change the .ai files.

**Comment by pixelzoom** [comment] 2017-10-18 17:19
While we're talking about the coins... In addition to the color issue:

• I'm wondering if these will even be interpreted as coins in this context. The salmon-colored coin doesn't look at all like a coin to me.
• I really can't make out the PhET logo and PhET girl on the coins, even on desktop.

**Comment by pixelzoom** [comment] 2017-10-18 17:22
For the "shapes" scene, we have 2 shapes that are circles. Should the sphere be changed to some non-circle shape, to prevent "discussion" confusion with the '1'?

![screenshot_409](https://user-images.githubusercontent.com/3046552/31732683-92a5cfc8-b3f6-11e7-84c2-a461aa92eaae.png)

**Comment by amanda-phet** [comment] 2017-10-18 17:23
Yeah I haven't been too thrilled with the coins either. They look very bland on this screen that has other fun, colorful objects.

**Comment by pixelzoom** [comment] 2017-10-18 17:26
Perhaps we should replace the coins with some other category of items?

**Comment by pixelzoom** [comment] 2017-10-18 17:28
Note to self: If we like the reflected dog and cat, we need to change the .ai files.

**Comment by amanda-phet** [comment] 2017-10-18 17:29
yes, perhaps... I will go back to brainstorming. One idea that was on the table was to use mystery presents similar to Balancing Act.

**Comment by kathy-phet** [comment] 2017-10-18 17:31
toy cars/trucks?
emojis?
toy sea animals or fish?

**Comment by kathy-phet** [comment] 2017-10-18 17:33
Also - Amanda, in playing I noticed equation lists the "1"? Did we discuss that? Should it be optional?

**Comment by pixelzoom** [comment] 2017-10-18 17:34
@amanda-phet said:
> One idea that was on the table was to use mystery presents similar to Balancing Act.

We discussed presents ala Balancing Act.  The issues were:

• The bow at the top doesn't facilitate stacking.  May not be a problem, or may look odd. Best to mock it up first.
• The icons will need to be labeled in some way (A, B, C) in order to identify them in discussions. This is not difficult, but will require creating the labels programmatically, and making them translatable.

**Comment by pixelzoom** [comment] 2017-10-18 17:36
@kathy-phet said:
> Also - Amanda, in playing I noticed equation lists the "1"? Did we discuss that? Should it be optional?

The current requirement was to hide the '1' coefficient for variable ('x') terms and show them for terms in the Basics screen.  I can certainly change that, but wanted you to know that it didn't happen by accident.

**Comment by pixelzoom** [comment] 2017-10-18 18:34
I've removed the "priority:top" label from this issue, since it's not currently blocking me.  But let's not lose momentum on this issue. Feedback on this issue was requested in the 6/8/2017 design meeting (3.5 months ago), and the coins have been in the sim for almost a month.  So we should be converging on resolution.

**Comment by clmccutchan** [comment] 2017-10-19 00:48
@pixelzoom  After reading this thread, I talk to @amanda-phet about boosting the contrast on the coins. See what you think of them now.

![basics-101817_new coins](https://user-images.githubusercontent.com/25354670/31749051-bc5616fa-b434-11e7-97b0-16415d4e18bf.png)

**Comment by pixelzoom** [comment] 2017-10-19 16:03
Like 'em.

**Comment by amanda-phet** [comment] 2017-10-19 16:39
@clmccutchan those look really great! Here's a quick comparison in context:

<img width="627" alt="screen shot 2017-10-19 at 10 36 20 am" src="https://user-images.githubusercontent.com/7852916/31782803-6579fd4e-b4b9-11e7-9a0a-a0d796dc9a6b.png">

<img width="623" alt="screen shot 2017-10-19 at 10 36 05 am" src="https://user-images.githubusercontent.com/7852916/31782814-6a4d4a38-b4b9-11e7-8055-863d267f1b2a.png">

I wish the "red" coin could like a tiny bit more "red".. even though it's kind of meant to be a copper coin I still like the color there (in the original coin).

**Comment by clmccutchan** [comment] 2017-10-19 19:42
@amanda-phet I can tweak the copper coin a bit to be more red, adjust the details on the cat, and then send you the .ai file.

**Comment by pixelzoom** [comment] 2017-10-23 18:57
There are now 2 “without shadows” files checked into GitHub: basic-artwork-without-shadows.ai (plural) and basic-artwork-without-shadow.ai (singular).   I can certainly check the dates and figure out which is the most current.  But that begs the question of how this happened.  @amanda-phet are you using files on your hard drive instead of the files from a GitHub working copy?

**Comment by pixelzoom** [comment] 2017-10-23 18:59
I'll fix things so that there is only 1 "without shadows" file.  It will be named basic-artwork-without-shadows.ai, for symmetry with basic-artwork-shadows.ai.

**Comment by pixelzoom** [comment] 2017-10-23 19:11
"without shadows" file is fixed, full github history was preserved.

**Comment by pixelzoom** [comment] 2017-10-23 19:17
I asked:
>  @amanda-phet are you using files on your hard drive instead of the files from a GitHub working copy?

I answered this question.  The new file you checked in still has the turtle layer "locked".  This is something that I fixed previously (and will now fix again).   So you must not be using the latest file from GitHub.  This is a problem.

**Comment by pixelzoom** [comment] 2017-10-23 19:31
The latest icons are integrated into https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.35/equality-explorer_en.html.

**Comment by amanda-phet** [comment] 2017-10-23 20:05
@pixelzoom Sorry about that, yes I must've been using the wrong version. I normally download the file directly but I got an updated one from @clmccutchan and used that one instead, so I'm sure that's where the problem arose. Thanks for taking care of it. 

I think all of the artwork is looking great!!

**Comment by amanda-phet** [comment] 2017-10-23 20:05
I would like some feedback from @kathy-phet and @ariel-phet before closing this issue.

**Comment by pixelzoom** [comment] 2017-10-23 20:11
@amanda-phet I'm also wondering about https://github.com/phetsims/equality-explorer/issues/6#issuecomment-337664459 - having 2 "circles" in the first scene.

**Comment by pixelzoom** [comment] 2017-10-23 20:13
In https://github.com/phetsims/equality-explorer/issues/6#issuecomment-337657365, @amanda-phet said:
> You're right about the black cat.. once I saw it in the equation I realized it blends in a little bit with the numbers. Maybe gray would be better?

@amanda-phet The cat is still black. Did you decide that this is not a problem?

**Comment by ariel-phet** [comment] 2017-10-24 17:48
@amanda-phet I think on the selection buttons is might be good to used a different shaped coin, but otherwise all looks pretty good. I personally don't have a issue with the cat getting confused for a number.

**Comment by amanda-phet** [comment] 2017-10-24 18:20
>For the "shapes" scene, we have 2 shapes that are circles. Should the sphere be changed to some non-circle shape, to prevent "discussion" confusion with the '1'?

I don't have a problem with two circles because one of them is a "1", and likely wouldn't be referred to as a circle. 

As for the cat, I think it looks more distinct from the number now because we flipped it and there is naturally more negative space between the number and the cat, so I'm good with it the way it is.

@ariel-phet thanks for the feedback.

**Comment by amanda-phet** [comment] 2017-10-24 20:14
@kathy-phet says they look great too.

In interviews, if students seem considerably more attracted to the animal scene than the coin scene, we may want to consider replacing coins with other fun artwork, but for now I like the idea of using an object that may be associated with a value other than weight. (ex: fruit could be cost, coins could be value).

**Closed as completed by amanda-phet** 2017-10-24 20:14 UTC
Labels: design:general
