### ISSUE TITLE
Pan does not work when dragging items from the toolbox.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#179] opened 2021-11-16 21:13 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/735.
When zoomed in, the sim does not pan around when dragging an object to the edge of the screen. Other methods of panning seem to work as expected. This is probably a fairly minor issue.

**Visuals**
![pandragobjects](https://user-images.githubusercontent.com/41024075/142065723-ed853357-e07f-434e-b89f-68c8cacf8688.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Equality Explorer‬
URL: https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-rc.1/phet/equality-explorer_all_phet.html?showPointerAreas
Version: 1.1.0-rc.1 2021-11-09 18:21:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2021-11-16 21:25
I'm not familiar with pan, so I'm not clear on what the expected behavor is here.  If it's not expected, there's nothing sim-specific (afaik) that is causing this.

@amanda-phet @jessegreenberg ?

**Comment by jessegreenberg** [comment] 2021-11-16 23:46
I would have expected it to keep the Node in view here. Pan and Zoom is not handling the creator pattern well, that is why it doesn't work when you pull out a term from the toolbar but does work for subsequent drags. It is not sim specific. Ill work on it in the above issue.

**Comment by pixelzoom** [comment] 2021-11-17 00:02
@amanda-phet Do you want this issue to be addressed for Equality Explorer 1.1 release?  Or do you want to make that decision after @jessegreenberg has investigated?

**Comment by pixelzoom** [comment] 2021-11-17 00:05
In https://github.com/phetsims/vegas/issues/97#issuecomment-969292488, @kathy-phet evaluated another problem with pan/zoom, and said:
> Thanks for making the issue, I agree this should not stop publication releases at the moment, and while I think we should investigate this issue and fix it in the long run, this issue seems like something that can wait a bit since its consequences are pretty minor. I've added it to quarterly planning to discuss if we do it in Q1 2022.

I suspect that this issue will not block Equality Explorer 1.1 for the same reasons, and should be included in the same "quarterly planning" discussion.  But @amanda-phet or @kathy-phet please confirm.

**Comment by pixelzoom** [comment] 2021-11-17 00:07
@KatieWoe could you please test this in a few other sims?  I'd like to verify that this is a general problem, so that this can be promoted to a general GitHub issue.  Test in master, try some sims that have toolboxes or buckets.

**Comment by KatieWoe** [comment] 2021-11-17 16:54
I am seeing the same thing in a number of sims on master.

**Comment by KatieWoe** [comment] 2021-11-17 16:59
@samreid this is in https://github.com/phetsims/qa/issues/736 as well

**Comment by pixelzoom** [comment] 2021-11-17 18:19
I've create general issue https://github.com/phetsims/joist/issues/769, assigned to @jessegreenberg.  

Labeling this issue as "on-hold" until https://github.com/phetsims/joist/issues/769 is addressed, or someone tells me that this is not a prerequisite for EqEx 1.1 release.

**Comment by jessegreenberg** [comment] 2021-11-18 02:50
@pixelzoom I discussed https://github.com/phetsims/joist/issues/769 with @kathy-phet in over slack and she said that the issue is something to work on now but that it does not need to be resolved before the EqEx 1.1 publication.

**Comment by pixelzoom** [comment] 2021-11-18 04:14
Thanks for the update @jessegreenberg.

Changing label to "deferred", to be addressed in a future release or MR.

**Comment by KatieWoe** [comment] 2021-12-03 20:05
Noting this in https://github.com/phetsims/qa/issues/748

**Comment by pixelzoom** [comment] 2021-12-03 20:21
@KatieWoe it would be preferrable to mention the general issue https://github.com/phetsims/joist/issues/769 in phetsims/qa#748, not this issue.

**Comment by KatieWoe** [comment] 2021-12-03 20:21
Sorry, I didn't see that one

**Comment by Nancy-Salpepi** [comment] 2024-11-18 21:05
Noting that I still see this issue in https://github.com/phetsims/qa/issues/1172 even though https://github.com/phetsims/joist/issues/769 was closed as completed.

**Comment by pixelzoom** [comment] 2024-11-19 17:44
Since https://github.com/phetsims/joist/issues/769 is closed, this should be working. So I'll investigate for 1.2 release.

**Comment by pixelzoom** [comment] 2024-11-19 19:37
I consulted with @jessegreenberg on this.  Reviewing https://github.com/phetsims/joist/issues/769, this was not a common-code fix, it was a programming error in CCK.  And I've made the same error here.

For pan-and-zoom to work properly, we need to call `press` with `event` and `targetNode` arguments.  Unfortunately the `targetNode` parameter is optional in DragListener:

```ts
  public override press( event: PressListenerEvent, targetNode?: Node, callback?: () => void ): boolean {
``` 

... so we sadly get no help from TypeScript when it's omitted. 

The fix in TermNode is therefore:

```diff
  public startDrag( event: PressListenerEvent ): void {
-    this.termDragListener.press( event );
+    this.termDragListener.press( event, this );
  }
```

@Nancy-Salpepi please review in main, close if OK.

**Comment by Nancy-Salpepi** [comment] 2024-11-19 20:03
Working well 🎉!
Closing.

**Closed as completed by Nancy-Salpepi** 2024-11-19 20:03 UTC
Labels: type:bug, status:ready-for-review
