### ISSUE TITLE
Design screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/equality-explorer#14] opened 2017-10-06 16:19 UTC

**Comment by pixelzoom** [comment] 2018-03-10 21:28
With the exception of the "lock" feature, the first 4 screens are feature complete.  So it's not impossible that we'll meet the "March 26 interviews" milestone.  And if we're going to do interviews, perhaps it's time to create screen icons.

**Comment by amanda-phet** [comment] 2018-03-20 19:29
@DianaTavares is working on these. Diana, please upload a screenshot of your design here and @pixelzoom will implement in code.

**Comment by DianaTavares** [comment] 2018-03-20 20:54
Here are the icons: 
![screen shot 2018-03-20 at 2 53 29 pm](https://user-images.githubusercontent.com/26031501/37682222-87f1cfc0-2c4e-11e8-85d3-9ecad00b3106.png)

**Comment by pixelzoom** [comment] 2018-03-20 21:08
@amanda-phet The navbar icon for Games doesn't match anything that will appear in the sim.  There would be no "+1", it would simply be "1".    OK to remove the "+"?  And consider using a more exciting number than "1" :)

**Comment by pixelzoom** [comment] 2018-03-20 23:19
Another nit... The solving screen icon shows "3x + 2 = 1x".   We never show "1x", we show "x".  And there's no value of x where this would be an equality.   So I'm going to change to "3x + 2 > x".

**Comment by DianaTavares** [comment] 2018-03-20 23:25
I am agree with delete te 1 in 1x, but in the other one  @amanda-phet told me that could be a good idea to use a - value for X (-1 in this case). One thing that I think is important in this icon is the = because the idea of solving is always with an equality.  Then we can use other expression with x=2 for example: 3x - 4 = x

**Comment by pixelzoom** [comment] 2018-03-20 23:30
OK, I'll change to `3x - 4 = x`.

**Comment by pixelzoom** [comment] 2018-03-20 23:31
@amanda-phet Make A Ten license file indicates that you are the creator of the PhET Girl juggling stars that appears in Make A Ten.  Is that correct?

**Comment by pixelzoom** [comment] 2018-03-20 23:33
Sorry @DianaTavares, my bad. `3x + 2 = x` is true for `x = -1`. I'll change it back to that.

**Comment by pixelzoom** [comment] 2018-03-20 23:54
Re PhET girl... Slack discussion with @amanda-phet:

Chris Malley [5:29 PM]
Make A Ten license file indicates that you are the creator of the PhET Girl juggling stars that appears in Make A Ten.  Is that correct?

Amanda McGarry [5:44 PM]
Mariah Hermsmeyer made the original PhET girl juggling blocks I just replaced it with stars.

Chris Malley [5:45 PM]
Mariah Hermsmeyer appears nowhere in the Make A Ten license file or credits.

Amanda McGarry [5:46 PM]
That's strange. She made all of the level icons too! I can make an issue to update that.

Chris Malley [5:46 PM]
Please tell me how you’d like this image credited in EqEx, and whether Mariah should be added to the credits.  I’m leave Make A Ten up to you — but this seems to be a chronic problem with image license files.

Amanda McGarry [5:47 PM]
Yes it does... We should include her in the license file but probably not the credits. Is that acceptable?

Or both if you think that's a better way to go about it

Chris Malley [5:48 PM]
You’re the only person credited under “Graphic Arts”.  And 100% of MAT images are annotated with “created by Amanda McGarry”.
Up to you for EqEx.

Amanda McGarry [5:49 PM]
That's really strange. I don't know how that happened. Thanks for letting me know.

Chris Malley [5:50 PM]
Someone other than developers should be reviewing the license file for accuracy of attribution.
I’ll let you broach that will Ariel.
Hard to understand the credits though, since that’s supposed to be approved as part of the checklist.

**Comment by pixelzoom** [comment] 2018-03-20 23:59
[1.0.0-dev.74](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.74/phet/equality-explorer_en_phet.html) has the screen icons as specified.   

To my eye, the navigation bar icons for the first 4 screens are too complex.

**Comment by pixelzoom** [comment] 2018-03-21 00:03
Suggestions:

Basics: Simplify to "2 apples > 1 orange".

Variables: remove the vertical space between terms, so it looks more like stacks.

Solving: Simplify the equation to something like "3x = 6".   I really don't think anyone is going to analyze the icons to the extent that we need to have a negative value for x here, or even x on both sides of the equation.

**Comment by DianaTavares** [comment] 2018-03-21 00:13
I like the suggestions :D

**Comment by pixelzoom** [comment] 2018-03-21 00:14
The above suggestions (https://github.com/phetsims/equality-explorer/issues/14#issuecomment-374798446) are demonstrated in [1.0.0-dev.75](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.75/phet/equality-explorer_en_phet.html).

**Comment by pixelzoom** [comment] 2018-03-21 17:13
Note to self: We may need larger versions of the apple and orange images for the Basics screen icons. They are currently being scale _up_ on the home screen, and therefore look a little fuzzy.

**Comment by amanda-phet** [comment] 2018-03-21 17:16
These are looking good! I like the simplifications you suggested, Chris. Just a couple requests. 

(1) Can you increase the padding around the icon for "Solving" screen? The 2x term looks a little too close to the edge to me. 

(2) I meant to respond to this question:
>And consider using a more exciting number than "1" :)

The +1 indicates an additional star that is added to your collection, not a total score. Can we change this back to +1?

**Comment by pixelzoom** [comment] 2018-03-21 19:02
@amanda-phet Your change requests are implemented in [1.0.0-dev.76](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.76/phet/equality-explorer_en_phet.html).

**Comment by amanda-phet** [comment] 2018-03-21 19:39
All looks good to me!

**Comment by pixelzoom** [comment] 2018-03-21 21:14
Reopening. I still need to create larger versions of the apple and orange PNG files, per https://github.com/phetsims/equality-explorer/issues/14#issuecomment-375023004.

**Comment by amanda-phet** [comment] 2018-03-21 21:22
Whoops, sorry about that.

**Comment by pixelzoom** [comment] 2018-03-21 21:26
Not a problem :)

**Comment by pixelzoom** [comment] 2018-03-21 21:50
Larger versions of the apple and orange are integrated. Closing.

**Comment by pixelzoom** [comment] 2018-03-21 22:06
Reopening.

The "Solving" screen has been renamed "Operations", see https://github.com/phetsims/equality-explorer/issues/43#issuecomment-375022168.   Do we need to revisit the screen icon? It was designed to communicate "solving".  Do we need something that communicates "operation"?

**Comment by amanda-phet** [comment] 2018-03-22 19:15
I thought about that and wondered if we should maybe do "3x + 4 = 7" and show "–4" drop. But I like how similar the icons are to the other screens (in size and style) that I think we can keep it. I would consider changing it if we notice in interview that students don't find the universal operator or don't understand the universal operator. So, I'll leave this open and add the interviews label.

**Closed as completed** 2018-03-23 17:50 UTC
Labels: design:general, design:interviews
