### ISSUE TITLE
multitouch problem with Android "quick settings" menu

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/equality-explorer#133] opened 2018-07-03 17:22 UTC
Test device: Galaxy Tab A

Operating System: Android 7.0

Browser: Chrome v. 67.0.3396.87

Problem description: For phetsims/QA/issues/131 When multiple items are dragged at the same time some items will not act properly and upon release will float in the air. These items do not return to the area where items can be chosen from and do not count toward the overall counter on the top of the screen. The sim continues to function as expected, however the floating items will remain until the items are either discarded or sorted. The floating items can not be manipulated other than discarding all other items or sorting. This creates some weird issues as well with the lock that manipulates both sides at the same time, deleting certain elements when they should not be.

Steps to reproduce: On any screen besides a game screen grab multiple items at the same time and move them onto the plates, if there are too many inputs some items should float above the plate where they shouldn't. This bug does not occur every time multiple inputs are given, and has also been noticed when only moving a single element. 

Screenshots:
This screenshot is from the Equality Explorer: Basics sim, however it is present in all equality explorer sims. 
![screenshot_20180703-110325](https://user-images.githubusercontent.com/30352536/42234407-af35abf0-7eb1-11e8-8534-c472b9fe8955.png)

<details>
<summary>
Troubleshooting Info:
</summary>
Name: ‪Equality Explorer‬
URL: http://phettest.colorado.edu/equality-explorer/equality-explorer_en.html?ea&brand=phet
Version: 1.0.0-dev.125 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1920x963
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2018-07-05 19:16
@JRomero0613 Have you been able to reproduce this on other touch devices (iOS, Chromebook,...), or is it specific to Android?

**Comment by JRomero0613** [comment] 2018-07-05 19:46
@pixelzoom It seems to be specific to Android as I have not seen the bug on iOS or Chromebook. After further testing it looks like multi touch is not the reason for the bug. It appears that when dragging an item around the screen if the Android drop down menu is pulled down while still holding the item it will freeze in mid-air.

**Comment by pixelzoom** [comment] 2018-07-06 16:22
@JRomero0613 What is "the Android drop down menu"?

**Comment by JRomero0613** [comment] 2018-07-06 16:59
@pixelzoom I think the actual term is the quick settings menu. This menu can be brought up on any Android by swiping down from the very top of the screen. There is a similar menu on iPad however it can not be pulled down while moving items unlike the Android quick settings menu.

**Comment by pixelzoom** [comment] 2018-07-06 17:01
@jonathanolson Can you comment on how pulling down the Android "quick settings" menu while dragging something might be affecting input event handling?

**Comment by pixelzoom** [comment] 2018-07-06 18:17
Also worth noting is that Android is not a supported platform.  From the FAQ at https://phet.colorado.edu/en/help-center/running-sims:

> Android: Not officially supported. If you are using the HTML5 sims on Android, we recommend using the latest version of Google Chrome and Android 4.1+.

**Comment by pixelzoom** [comment] 2018-07-06 18:18
Also worth noting is that Android is not a supported platform.  From the FAQ at https://phet.colorado.edu/en/help-center/running-sims:

> Android: Not officially supported. If you are using the HTML5 sims on Android, we recommend using the latest version of Google Chrome and Android 4.1+.

So my feeling is that, unless this is trivial to fix, we should ignore it for 1.0 release and create a more general issue for scenery.  @amanda-phet @ariel-phet Do you agree?

**Comment by amanda-phet** [comment] 2018-07-06 20:06
My thoughts: While we don't officially support android, we *do* have an app, and that app should be considered "supported." @lmulhall-phet was able to reproduce this bug in the android app (using Area Builder). But, as soon as he picked up the square it was fine, and this is also easily remedied using reset-all. 

For the purposes of Equality Explorer, I do not think we need to invest in this particular bug. However,  I think we need to have a discussion about if we are supporting android if we have an android app, and decide if we want to address this bug (that can happen with any sim).

**Comment by pixelzoom** [comment] 2018-07-06 20:16
I've created a more general scenery issue: https://github.com/phetsims/scenery/issues/828.  

Marking this issue as deferred, not to be addressed for 1.0 release.

**Comment by pixelzoom** [comment] 2018-07-11 17:00
I'm going to close this issue at "will not fix", since this is not a sim-specific problem. phetsims/scenery#828 will involve deciding how/whether to address, and how to patch all sims.

**Closed as completed by pixelzoom** 2018-07-11 17:00 UTC
Labels: type:bug, type:wontfix, type:multitouch, priority:5-deferred
