### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#193] opened 2022-10-10 17:34 UTC
Also in Basics and Two Variables
```
equality-explorer : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665411155859%22%2C%22timestamp%22%3A1665416550895%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:157:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 8:12:35 AM

----------------------------------

equality-explorer : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/studio/?sim=equality-explorer&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665411155859%22%2C%22timestamp%22%3A1665414376733%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:157:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 8:12:35 AM

----------------------------------

equality-explorer : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/phet-io-wrappers/phet-io-wrappers-tests.html?sim=equality-explorer&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: equality-explorer: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/tandem/js/PhetioObject.js:144:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/tandem/js/PhetioObject.js:117:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/ReadOnlyProperty.js:91:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/BooleanProperty.js:20:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/EnabledComponent.js:31:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/sun/js/buttons/ButtonModel.js:53:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:157:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 8:12:35 AM

----------------------------------

equality-explorer : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/phet-io-wrappers/phet-io-wrappers-tests.html?sim=equality-explorer
30 out of 31 tests passed. 1 failed.
SimTests: equality-explorer: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/tandem/js/PhetioObject.js:144:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/tandem/js/PhetioObject.js:117:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/ReadOnlyProperty.js:91:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/BooleanProperty.js:20:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/axon/js/EnabledComponent.js:31:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/sun/js/buttons/ButtonModel.js:53:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665411155859/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:214:16)
at initializePhetioObject (PhetioObject.ts:186:11)
at (ReadOnlyProperty.ts:157:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (PushButtonModel.ts:71:4)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 8:12:35 AM
```

**Comment by pixelzoom** [comment] 2022-10-11 02:12
In Slack, @samreid suggested:
>  maybe this section would work? https://github.com/phetsims/phet-io/blob/d4b895df6c8668ac6582831eddbbfa5ed74b40ba/doc/phet-io-instrumentation-technical-guide.md#validation
> adding this entry to package.json:

```json
    "phet-io": {
      "validation": false
    }
```

In the above commits, I believe that I've turned off PhET-iO valiation tests for CT.  Unfortunately I can't stick around to confirm, since I'm on vacation.  @KatieWoe if this looks OK after a CT cycle, please close.  Otherwise assign back to me.

**Comment by pixelzoom** [comment] 2022-10-11 12:41
This has failed CT for (at least) 4 consecutive cycles since I added `validation: false`.   I confirmed that I added where it occurs in package.json for other sims (arithmetic, bending-light,...

@samreid @zepumph could one of you please investigate?

**Comment by pixelzoom** [comment] 2022-10-11 12:44
I'll also note that this fails in my local working copy with phetmarks.  Running with the defaults for "studio" mode, which include:

http://localhost:8080/studio/?sim=equality-explorer&locales=*&keyboardLocaleSwitcher&phetioWrapperDebug=true&phetioElementsDisplay=all

Note that the default includes:

<img width="368" alt="screenshot_1931" src="https://user-images.githubusercontent.com/3046552/195093803-54a1dc72-7ed6-447b-86a5-1dc42ce7c787.png">

... and I'm guessing that "Simulation Default" means "what's specified in package.json".

**Comment by pixelzoom** [comment] 2022-10-11 12:49
Apparently it's necessary to run `grunt update`, and that's not mentioned in the technical guide (it is now).  So I ran `grunt update` for all sims in the suite, verified that they run locally with default Studio settings, and pushed. 

I'll wait to see if this makes CT happy.

**Comment by zepumph** [comment] 2022-10-11 15:09
Right. The only way any package.json flags make it into the development HTML runnable is by regenerating that runnable in `grunt generate-development-html`. 

Good luck! Please do assign us any issues that involve phet-io assertions from here. Ideally validation:false would be enough to ignore everything you'd encounter in PhET-iO.

**Comment by pixelzoom** [comment] 2022-10-11 21:30
CT has been happy for several cycles. Closing.

**Closed as completed by pixelzoom** 2022-10-11 21:30 UTC
Labels: type:automated-testing
