### ISSUE TITLE
Grab sound volume inconsistent 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#215] opened 2024-11-18 17:56 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1 and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1172 and related to https://github.com/phetsims/equality-explorer/issues/181 the grab sound when pulling an item out of the toolbox is much lower than the grab sound when interacting with an item on the scale and also lower than the release sound. This happens on all screens, except the Solve it! screen. 

**Steps to reproduce**
1. On the Basics screen, grab a blue block from the toolbox and put it on the scale.
2. Grab the blue block on the scale--this grab sound is much louder.
3. Grab another blue block from the toolbox and release it -- release sound is much louder than the grab sound

**Visuals**
(Sorry video has slightly different steps)
https://github.com/user-attachments/assets/9dc40ccf-10fd-48b0-949a-5de12ce3970f

**Comment by pixelzoom** [comment] 2024-11-19 18:46
Reproduced in main.

Dragging a term out of the toolbox uses PhET's [Creator (with Drag Forwarding)](https://github.com/phetsims/phet-info/blob/main/doc/phet-software-design-patterns.md#creator-with-drag-forwarding) pattern.  See TermCreatorNode line 57, where`DragListener.createForwardingListener` is called, which forwards the drag event to the new TermNode instance in EqualityExplorerSceneNode:

```ts
      // start a drag cycle by forwarding the event to termNode.
      if ( event ) {
        termNode.startDrag( event );
      }
```

It looks to me like the output levels for the default sounds are not being properly initialized in this case. Or maybe they are not properly initialized for the general SoundDragListener case?  See `TermDragListener extends SoundDragListener`. 

I'll need to consult with @jessegreenberg on this one, since I believe he recently did an overhaul of scenery's 'drag listener' stack.

**Comment by pixelzoom** [comment] 2024-11-19 19:25
@jessegreenberg and I discussed.  He's going to have a look offline.  It seems like initialOutputLevel might be applied twice?

We tried this change in SceneryPhetConstants and output level was reduced for all drags:

```diff
-  DEFAULT_DRAG_CLIP_OPTIONS: { initialOutputLevel: 0.4 },
+  DEFAULT_DRAG_CLIP_OPTIONS: { initialOutputLevel: 0.1 },
```

We tried this change in SceneryPhetConstants and sound was off for all drags:

```diff
-  DEFAULT_DRAG_CLIP_OPTIONS: { initialOutputLevel: 0.4 },
+  DEFAULT_DRAG_CLIP_OPTIONS: { initialOutputLevel: 0 },
```

**Comment by jessegreenberg** [comment] 2024-11-19 21:07
I identified the issue to be in the "creator" pattern rather than in `SoundDragListener`. The problem comes from calling `play` on the `SoundClip` immediately after it is added to the `soundManager`.

Creating a new term `Node` creates a new `SoundDragListener` - which in `wireSoundsToDragCallbacks` creates a new `SoundClip` and adds it to the `soundManager`.  Then the event for the drag `start` is forwarded to call `play` immediately.

I found that this patch makes the problem go away
```patch
Subject: [PATCH] node -> Node in comments and documentation, see https://github.com/phetsims/scenery/issues/1661
---
Index: js/SoundRichDragListener.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/SoundRichDragListener.ts b/js/SoundRichDragListener.ts
--- a/js/SoundRichDragListener.ts	(revision 7de94b6ebedbcfb2708d55e4c4dcbc9fd3c3ffe0)
+++ b/js/SoundRichDragListener.ts	(date 1732049026513)
@@ -121,7 +121,7 @@
 
         // @ts-expect-error - see above note.
         previousStart && previousStart( ...args );
-        dragClip!.play();
+        dragClip!.play( 0.1 );
       };
     }
 ```

But I also noticed that sometimes the release sound is cut short when I drop a term back in the toolbox, because the `releaseClip` is disposed before the sound can finish. A delay on the `releaseClip` prevents it from playing at all.

Maybe for the creator pattern, we need to have different `SoundClip`s added to the `soundManager` so they can play separately from the instances that are created and destroyed.

But I think @jbphet may have a better recommendation.

**Comment by pixelzoom** [comment] 2024-11-19 22:28
@jbphet do you have a better recommendation than the patch proposed in https://github.com/phetsims/equality-explorer/issues/215#issuecomment-2486755076?

**Comment by pixelzoom** [comment] 2024-11-19 23:09
> I identified the issue to be in the "creator" pattern rather than in `SoundDragListener` ... 

The creator pattern is a well-establish PhET pattern, the defacto way that we (for example) drag things out of a toolbox or bucket. Yes, the creator pattern results in a Node being created and dragged immediately. But why is this a problem with the creator pattern? Not supporting the creator pattern is a problem with `SoundDragListener`, not a problem with the creator pattern.

> I found that this patch makes the problem go away ... But I think @jbphet may have a better recommendation.

The patch adds a delay to every playback, and (as you said) does not address release sounds being cut short. So I'm not wild about this direction.

@jbphet do you have a better recommendation than the patch proposed in https://github.com/phetsims/equality-explorer/issues/215#issuecomment-2486755076?

**Comment by jessegreenberg** [comment] 2024-11-19 23:17
Right, to clarify I am not proposing that patch, I am proposing:
> Maybe for the creator pattern, we need to have different SoundClips added to the soundManager so they can play separately from the instances that are created and destroyed.

**Comment by pixelzoom** [comment] 2024-11-19 23:37
If I have some TermNodes that are created via the creator pattern and some that are not, then I'm going to have new problems if I need to manage whether their drag listeners have sounds or whether there are separate sounds.  And subsequent drags of a TermNodes that was originally created using the creator pattern should use the drag listener sounds.

We could investigate adding options to SoundDragListener and SoundKeyboardDragListener (or SoundClip?) that specifies a `play` delay (for the grab sound) and a `stop` delay (for release).   But even that sounds like a sim-side headache.

Before doing anything, I'd like to understand why there's such an obvious difference in volume when the grab sound is played immediately after instantiation of the SoundDragListener.  If it's because the output level hasn't had time to stabilize, then I'd expect it to be _louder_, not softer, because the default is `initialOutputLevel: 0.4`.

**Comment by jessegreenberg** [comment] 2024-11-20 00:13
Yes, that makes sense. I think it is a general tambo or browser bug. In this patch in the tambo demo, the sound is quiet.

<details>

```patch
Subject: [PATCH] node -> Node in comments and documentation, see https://github.com/phetsims/scenery/issues/1661
---
Index: js/demo/testing/view/TestingScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/demo/testing/view/TestingScreenView.ts b/js/demo/testing/view/TestingScreenView.ts
--- a/js/demo/testing/view/TestingScreenView.ts	(revision 79b3f2ec169c5aad90ccdc942f270eae4d1cbb85)
+++ b/js/demo/testing/view/TestingScreenView.ts	(date 1732061231759)
@@ -26,6 +26,7 @@
 import rhodesChord_mp3 from '../../../../sounds/demo-and-test/rhodesChord_mp3.js';
 import thunder_mp3 from '../../../../sounds/demo-and-test/thunder_mp3.js';
 import emptyApartmentBedroom06Resampled_mp3 from '../../../../sounds/emptyApartmentBedroom06Resampled_mp3.js';
+import grab_mp3 from '../../../../sounds/grab_mp3.js';
 import nullSoundPlayer from '../../../nullSoundPlayer.js';
 import phetAudioContext from '../../../phetAudioContext.js';
 import SoundClip from '../../../sound-generators/SoundClip.js';
@@ -189,7 +190,9 @@
     convolver.buffer = emptyApartmentBedroom06Resampled_mp3.audioBufferProperty.value;
 
     // sound clips to be played
-    const shortSoundNormal = new SoundClip( checkboxChecked_mp3 );
+    const shortSoundNormal = new SoundClip( checkboxChecked_mp3, {
+      initialOutputLevel: 0 // turn off this sound for testing
+    } );
     soundManager.addSoundGenerator( shortSoundNormal );
     const shortSoundWithReverb = new SoundClip( checkboxChecked_mp3, {
       additionalAudioNodes: [ convolver ]
@@ -203,7 +206,18 @@
     const playNormalSoundButton = new TextPushButton( 'Normal Sound Clip', {
       baseColor: '#CCFF00',
       font: buttonFont,
-      soundPlayer: shortSoundNormal
+      soundPlayer: shortSoundNormal,
+      listener: () => {
+        const soundClip = new SoundClip( grab_mp3 );
+
+        soundManager.addSoundGenerator( soundClip );
+        soundClip.play();
+
+        // Remove the sound clip quickly for testing.
+        window.setTimeout( () => {
+          soundManager.removeSoundGenerator( soundClip );
+        }, 100 );
+      }
     } );
 
     // add button to play the sound with the reverb added in the signal path
```
</details>

But move `const soundClip = new SoundClip( grab_mp3 );` outside of the button listener and the sound is louder.

To reproduce, apply this patch, go to the "Testing" screen of the tambo demo, and press "Normal Sound Clip" button.

**Comment by pixelzoom** [comment] 2024-11-20 18:20
In https://github.com/phetsims/scenery-phet/issues/889, we noted that the API for "sound drag listeners" has some inherent problems and needs to change.  That work will not be done in time to create our 1.2 release branch.   So in this sim, I've reverted to using a DragListener, and playing the default grab/release sounds in its start/end callbacks.   A future release can consider using SoundDragListener, or (better) add keyboard input and use RichDragListener.

@Nancy-Salpepi please review in main, close if it looks (sounds?) OK.

**Comment by Nancy-Salpepi** [comment] 2024-11-20 19:53
It sounds great! It also changes something else that had been bothering me --when combining 2 terms so they add up to zero, there was no release sound in the dev version. In main, I now hear a release sound.
Dev version:

https://github.com/user-attachments/assets/86920b17-b63d-43b2-8746-413590f31145

on main:

https://github.com/user-attachments/assets/0b8407cc-a305-4482-9bec-9eefbae7db08

@pixelzoom I just want to make sure that you also like this change. Close if you are good with it!

**Comment by pixelzoom** [comment] 2024-11-21 19:18
Thanks for checking @Nancy-Salpepi  -- yes, I like it too.  

Closing.

**Closed as completed by pixelzoom** 2024-11-21 19:18 UTC
Labels: type:bug, status:ready-for-review, dev:sound
