### ISSUE TITLE
Failure in lock Scenario 8

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#142] opened 2018-07-16 15:52 UTC
Both iPad 2 using Safari and a Windows 10 laptop using Firefox fail scenario 8.  Instead of the terms returning to their toolboxes, the dragged and equivalent terms will both be added back to their plates.  The right will therefore fill beyond capacity.
Screenshot:
![too many 1s](https://user-images.githubusercontent.com/41024075/42768824-b9726974-88dd-11e8-913c-067f90e6aada.PNG)
This is for phetsims/QA/issues/144
Will continue to add to in comments if more devices and browsers are found.

**Comment by pixelzoom** [comment] 2018-07-16 15:53
@KatieWoe This looks like a duplicate of https://github.com/phetsims/equality-explorer/issues/138. Do you agree?

**Comment by KatieWoe** [comment] 2018-07-16 15:58
Yes it does look similar.

**Comment by pixelzoom** [comment] 2018-07-16 16:01
Closing as duplicate of #138.

**Closed as completed by pixelzoom** 2018-07-16 16:01 UTC
Labels: type:bug, type:duplicate
