### ISSUE TITLE
Scale is thrown off when one side is full and lock is on

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#171] opened 2021-11-05 20:32 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/732. Seems to happen in published 1.0.14.
If one side of the scale is full of one type of object, the other side has another type of object, and the scale is locked, moving one of the objects can cause either floating objects, an unbalanced scale when it should be balanced, or objects return to the buckets that shouldn't. If the scale indicator arrow is red, a block will float if you try to grab it. If it isn't, the balance incorrectly tries to balance itself, leading to an incorrect equality reading that sticks around and becomes more obvious if you reset the sim.
**Steps to reproduce**
1. Go to the Variables screen
2. Fully fill one side with 1 circles
3. partially fill the other side with x blocks
4. Click the lock
5. Try to grab an x block
6. repeat

**Visuals**
![offscale](https://user-images.githubusercontent.com/41024075/140574778-3e49d236-efc4-4dc3-8aed-444bda31adb2.gif)
![floatblock](https://user-images.githubusercontent.com/41024075/140574779-c8b50ba5-597e-4771-9be0-6deb694168e4.gif)
<img width="960" alt="unbalancescales" src="https://user-images.githubusercontent.com/41024075/140574782-786b8918-31c0-4678-8910-25eb11e9e058.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Equality Explorer‬
URL: https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.4/phet/equality-explorer_all_phet.html
Version: 1.1.0-dev.4 2021-11-03 18:34:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2021-11-05 20:49
Reminder to self that there is an entire document that described "lock feature scenario", see https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md.  Might need to update/extend that document, if something was missed.

**Comment by KatieWoe** [comment] 2021-11-05 22:54
May be connected to scenario 11 in that document https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md#scenario-11

**Comment by pixelzoom** [comment] 2021-11-08 19:04
Reproduced in 1.0.0-dev.4 and master.   

This is behaving oddly in 1.0.0-dev.4 because there is actually an assertion failure. 

Here's the assertion failure in unbuilt master:

```
assert.js:25 Uncaught Error: Assertion failed: term already on plate: VariableTerm: 1/1 Variable: x=1
    at window.assertions.assertFunction (assert.js:25)
    at VariableTermCreator.putTermOnPlate (TermCreator.js:361)
    at VariableTerm.animationCompletedCallback (SeparateTermsDragListener.js:177)
    at VariableTerm.step (EqualityExplorerMovable.js:173)
    at VariableTermCreator.step (TermCreator.js:261)
    at EqualityExplorerScene.js:177
    at Array.forEach (<anonymous>)
    at VariablesScene.step (EqualityExplorerScene.js:177)
    at VariablesModel.step (EqualityExplorerModel.js:50)
    at Sim.js:293
window.assertions.assertFunction @ assert.js:25
putTermOnPlate @ TermCreator.js:361
animationCompletedCallback @ SeparateTermsDragListener.js:177
step @ EqualityExplorerMovable.js:173
step @ TermCreator.js:261
(anonymous) @ EqualityExplorerScene.js:177
step @ EqualityExplorerScene.js:177
step @ EqualityExplorerModel.js:50
(anonymous) @ Sim.js:293
```

**Comment by pixelzoom** [comment] 2021-11-08 19:07
[Scenario 11](https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md#scenario-11) is indeed the failing scenario.  It can be reproduced more quickly by limiting the number of items that can be put on a plate, e.g. `?rows=2&columns=2&showGrid`

Checking other screens that have the lock feature...

This also occurs in the _Numbers_ screen, where the stack trace is:

```
Uncaught Error: Assertion failed: term already on plate: ConstantTerm: -1/1
    at window.assertions.assertFunction (assert.js:25)
    at ConstantTermCreator.putTermOnPlate (TermCreator.js:361)
    at ConstantTerm.animationCompletedCallback (SeparateTermsDragListener.js:177)
    at ConstantTerm.step (EqualityExplorerMovable.js:173)
    at ConstantTermCreator.step (TermCreator.js:261)
    at EqualityExplorerScene.js:177
    at Array.forEach (<anonymous>)
    at NumbersScene.step (EqualityExplorerScene.js:177)
    at NumbersModel.step (EqualityExplorerModel.js:50)
    at Sim.js:293
```

Does not occur in the _Operations_ screen.

**Comment by pixelzoom** [comment] 2021-11-08 19:30
Clicking on a term causes it to pop up.  In this case, it needs to be animated back to the plate.  But as far as the model is concerned, the term is still on the plate.  So at the end of the animation, trying to put the term on the plate fails, because it's already on the plate.

In the worst case, this could be addressed by removing this assertion in TermCreator.js

```
  putTermOnPlate( term, cell ) {
    assert && assert( !this.termsOnPlate.includes( term ), `term already on plate: ${term}` );
```

But I'm going to investigate a more proper solution. The term should be marked as being off the plate when it pops up.

**Comment by pixelzoom** [comment] 2021-11-08 20:01
Fixed in the above commit.  

@KatieWoe please review in master. Also check the general behavior of dragging terms on/off the plate, since this fix involved touching that drag listener.   

Note that you can speed up your testing by running with `?ea&rows=2&columns=2&showGrid`.

**Comment by KatieWoe** [comment] 2021-11-08 21:13
Looks fixed on master. I didn't see any problems putting objects on the scale or taking them off. If you have any more specific tests, let me know. I did notice that cancelations when they should be possible aren't, but it seems like a much less serious problem.
![wontcancel](https://user-images.githubusercontent.com/41024075/140819022-8c5dbafc-256b-4459-b8b3-b853f528bbd7.gif)

**Comment by pixelzoom** [comment] 2021-11-08 22:20
Thanks @KatieWoe.  What you've described in https://github.com/phetsims/equality-explorer/issues/171#issuecomment-963579116 is a different issue (an unsupported scenario), so I've created https://github.com/phetsims/equality-explorer/issues/173 to track it. 

This issue can be closed.

**Closed as completed by pixelzoom** 2021-11-08 22:20 UTC
Labels: type:bug, status:ready-for-review
